#!/bin/sh

rm -fr .venv || true

python -m venv .venv

. ./.venv/bin/activate

python -m pip install --upgrade pip

pip install -r ./examples/requirements.txt

pip install -r ./examples/requirements.dev.txt
